name: Build .exe on Windows

on:
  schedule:
    - cron: "0 0 * * 0"  # Uruchamiaj raz w tygodniu o północy w niedzielę
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install PyInstaller  # Dodaj ten etap
      run: pip install pyinstaller

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Build .exe
      run: pyinstaller main.py --onefile

    - name: Upload .exe artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-exe
        path: dist/main.exe

    - name: Save .exe
      run: mv dist/main.exe main.exe

    - name: Commit and push .exe to repo
      run: |
        git add main.exe
        git commit -m "Add main.exe"
        git push --set-upstream origin main
      env:
       GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
