name: Build .exe

on:
  push:
    branches:
      - main  # Zmień to na główną gałąź repozytorium

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11  # Wybierz odpowiednią wersję Pythona

    - name: Install dependencies and build .exe
      run: python build.py

    - name: Upload .exe artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-exe  # Nazwa archiwum
        path: dist/main.exe  # Ścieżka do pliku .exe
